AWSTemplateFormatVersion: '2010-09-09'
Description:   AWS Lambda Provisioned Concurrency AutoScaling Demo with Application AutoScaling

Parameters:
  FunctionStackName:
    Description: The name of the CloudFormation Stack that deployed the Function
    Type: String
  ScalingPolicyTargetValue:
    Description: The % of utilization to keep as Provisioned Concurrency
    Type: Number
    Default: 0.7
  ScaleInSchedule:
    Type: String
    Default: cron(00 * * * ? *)
  ScaleOutSchedule:
    Type: String
    Default: cron(30 * * * ? *)
    
Resources:
  WhatsNewLambdaPcFunctionScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties: 
      ServiceNamespace: lambda
      ScalableDimension: lambda:function:ProvisionedConcurrency
      MaxCapacity: 100
      MinCapacity: 1
      ResourceId: !Sub 'function:{{resolve:ssm:/${FunctionStackName}/function/alias}}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency'
      ScheduledActions:
        - ScheduledActionName: ScaleOut
          Schedule: !Ref ScaleOutSchedule
          ScalableTargetAction:
            MaxCapacity: 50
            MinCapacity: 50
        - ScheduledActionName: ScaleIn
          Schedule: !Ref ScaleInSchedule
          ScalableTargetAction:
            MaxCapacity: 1
            MinCapacity: 1
  WhatsNewLambdaPcFunctionScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-LambdaPC-TargetTrackingPolicy'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WhatsNewLambdaPcFunctionScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        DisableScaleIn: False  # Default: False
        ScaleInCooldown: 0     # Default: 0
        ScaleOutCooldown: 0    # Default: 0
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
        TargetValue: !Ref ScalingPolicyTargetValue
