version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "whats-new-lambda-pc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tgrtypz6pq8i"
s3_prefix = "whats-new-lambda-pc"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Alias=\"live\" ProvisionedConcurrencyExecutions=\"1\""
