AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda Provisioned Concurrency AutoScaling Demo

Parameters:
  Alias:
    Description: AutoPublishAlias name
    Type: String
    Default: live
  ProvisionedConcurrencyExecutions:
    Description: Number of PC executions
    Type: Number
    Default: 1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"

Resources:
  WhatsNewLambdaPcFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-pc-function/
      Handler: lambda-pc
      Runtime: go1.x
      MemorySize: 256
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      AutoPublishAlias: !Ref Alias
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: !Ref ProvisionedConcurrencyExecutions
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
  WhatsNewLambdaPcFunctionParameterAlias:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${AWS::StackName}/function/alias'
      Tier: Standard
      Type: String
      Value: !Sub '${WhatsNewLambdaPcFunction}:${Alias}'
  WhatsNewLambdaPcFunctionParameterName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${AWS::StackName}/function/name'
      Tier: Standard
      Type: String
      Value: !Sub '${WhatsNewLambdaPcFunction}'

  CWDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardName: !Sub "LambdaPC-${AWS::StackName}"
      DashboardBody: !Sub |
        {"widgets":[{"height":9,"width":12,"y":0,"x":0,"type":"metric","properties":{"period":1,"metrics":[["AWS/Lambda","Duration","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"stat":"Minimum"}],["...",{"stat":"Average"}],["...",{"stat":"Maximum"}]],"region":"ap-southeast-2","view":"timeSeries","stacked":false,"title":"Execution Duration","liveData":true}},{"height":9,"width":12,"y":0,"x":12,"type":"metric","properties":{"metrics":[["AWS/Lambda","ConcurrentExecutions","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"label":"ConcurrentExecutions"}],[".","ProvisionedConcurrentExecutions",".","."],[".","ProvisionedConcurrencySpilloverInvocations",".","."]],"period":1,"region":"ap-southeast-2","title":"Concurrent executions","view":"timeSeries","stacked":false,"liveData":true,"stat":"Maximum"}},{"height":6,"width":15,"y":12,"x":0,"type":"metric","properties":{"period":1,"metrics":[["AWS/Lambda","ProvisionedConcurrencyUtilization","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"stat":"Maximum"}]],"region":"ap-southeast-2","yAxis":{"left":{"max":1}},"view":"timeSeries","stacked":false,"title":"ProvisionedConcurrencyUtilization","liveData":true}},{"height":3,"width":15,"y":9,"x":0,"type":"metric","properties":{"metrics":[["WhatsNew-LambdaPC","Latency","CATEGORY","performance","TEST_NAME","${WhatsNewLambdaPcFunction}","TYPE","latency",{"label":"Latency - Max","stat":"Maximum"}],["...",{"label":"Latency - P99","stat":"p99"}],["...",{"label":"Latency - Avg"}],["...",{"label":"Samples","stat":"SampleCount"}]],"view":"singleValue","stacked":true,"region":"ap-southeast-2","start":"-PT1H","end":"P0D","stat":"Average","period":1,"setPeriodToTimeRange":true,"title":"Artillery Data"}},{"type":"metric","x":15,"y":9,"width":9,"height":3,"properties":{"metrics":[["AWS/Lambda","ProvisionedConcurrentExecutions","FunctionName","${WhatsNewLambdaPcFunction}"],[".","ProvisionedConcurrencySpilloverInvocations",".","."],[".","ProvisionedConcurrencyInvocations",".",".",{"visible":false,"stat":"Sum"}]],"view":"singleValue","region":"ap-southeast-2","stat":"Maximum","period":5,"title":"PC Utilization"}}]}{"widgets":[{"height":9,"width":12,"y":0,"x":0,"type":"metric","properties":{"period":1,"metrics":[["AWS/Lambda","Duration","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"stat":"Minimum"}],["...",{"stat":"Average"}],["...",{"stat":"Maximum"}]],"region":"ap-southeast-2","view":"timeSeries","stacked":false,"title":"Execution Duration","liveData":true}},{"height":9,"width":12,"y":0,"x":12,"type":"metric","properties":{"metrics":[["AWS/Lambda","ConcurrentExecutions","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"label":"ConcurrentExecutions"}],[".","ProvisionedConcurrentExecutions",".","."],[".","ProvisionedConcurrencySpilloverInvocations",".","."]],"period":1,"region":"ap-southeast-2","title":"Concurrent executions","view":"timeSeries","stacked":false,"liveData":true,"stat":"Maximum"}},{"height":6,"width":15,"y":12,"x":0,"type":"metric","properties":{"period":1,"metrics":[["AWS/Lambda","ProvisionedConcurrencyUtilization","FunctionName","${WhatsNewLambdaPcFunction}","Resource","${WhatsNewLambdaPcFunction}:${Alias}",{"stat":"Maximum"}]],"region":"ap-southeast-2","yAxis":{"left":{"max":1}},"view":"timeSeries","stacked":false,"title":"ProvisionedConcurrencyUtilization","liveData":true}},{"height":3,"width":15,"y":9,"x":0,"type":"metric","properties":{"metrics":[["WhatsNew-LambdaPC","Latency","CATEGORY","performance","TEST_NAME","${WhatsNewLambdaPcFunction}","TYPE","latency",{"label":"Latency - Max","stat":"Maximum"}],["...",{"label":"Latency - P99","stat":"p99"}],["...",{"label":"Latency - Avg"}],["...",{"label":"Samples","stat":"SampleCount"}]],"view":"singleValue","stacked":true,"region":"ap-southeast-2","start":"-PT1H","end":"P0D","stat":"Average","period":1,"setPeriodToTimeRange":true,"title":"Artillery Data"}},{"type":"metric","x":15,"y":9,"width":9,"height":3,"properties":{"metrics":[["AWS/Lambda","ProvisionedConcurrentExecutions","FunctionName","${WhatsNewLambdaPcFunction}"],[".","ProvisionedConcurrencySpilloverInvocations",".","."],[".","ProvisionedConcurrencyInvocations",".",".",{"visible":false,"stat":"Sum"}]],"view":"singleValue","region":"ap-southeast-2","stat":"Maximum","period":5,"title":"PC Utilization"}}]}

Outputs:
  Dashboard:
    Description: "Dashboard created to monitor Lambda function"
    Value: !Sub |
        "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home#dashboards:name=${CWDashboard}"

  WhatsNewLambdaPcFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt WhatsNewLambdaPcFunction.Arn
  WhatsNewLambdaPcFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WhatsNewLambdaPcFunctionRole.Arn
